#+title:      Cleavir
#+date:      <2024-08-16 fr.>
#+OPTIONS: author:nil
#+STARTUP: inlineimages

#+hugo_base_dir: ~/Dokumenter/sicl-hugo
#+hugo_selection: posts
#+hugo_front_matter_format: yaml

* Cleavir

This is a continuation of Strands SICL (SICL implements Common
Lisp). Although most of the compiler can itself be written in Common
Lisp  to be a compliant Compiler it must eventually compile  to
machine code. Today this is done by the SBCL compiler. To make the
compiler work standalone this will need to be implemented and thus I have drafted this
proposal. It is criteria that the compiler need to be fast and good. A speed
goal for the generated code would be to be within a factor of 3 of a C compiler. The
compiler itself must compile fast similarly to the SBCL compiler today or
better. As SICL itself it is written in Common lisp.This is a preliminary draft of my
ideas of how this can be accomplished, subject approval by Dr Strand.

 * Clostrum
   [[http://metamodular.com/SICL/environments.pdf][First class global environment in common lisp]]
 * Eclector
   Portable reader
 * Cleavir
   Framework for common Lisp compilers
 * Cluster
   Assembler that accepts input as objects

* The 25 special forms of common lisp

By the time the code gets to the compiler the macro-expander has already run and all that
is left are the 25 special forms that need to be compiled.

| block     | let*                 | return-from     |
| catch     | load-time-value      | setq            |
| eval-when | locally              | symbol-macrolet |
| flet      | macrolet             | tagbody         |
| function  | multiple-value-call  | the             |
| go        | multiple-value-prog1 | throw           |
| if        | progn                | unwind-protect  |
| labels    | progv                |                 |
| let       | quote                |                 |
 
* Structure

#+ATTR_ORG: :width 600

[[../../static/images/Cleavir.svg]]


# Local Variables:
# eval: (set-fill-column 90)
# eval: (auto-fill-mode t)
# eval: (org-hugo-auto-export-mode t)
# End:

#  LocalWords:  inlining typecheck  svg jmp Runtime invariants progv setq prog flet
#  LocalWords:  macrolet tagbody eval SICL Clostrum Cleavir
